In [19]:
import pandas as pd
import numpy  as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

# Load CSV file

In [4]:
df= pd.read_csv("lending_data.csv")
df

loan_size  interest_rate  borrower_income  debt_to_income  \
0        10700.0          7.672            52800        0.431818   
1         8400.0          6.692            43600        0.311927   
2         9000.0          6.963            46100        0.349241   
3        10700.0          7.664            52700        0.430740   
4        10800.0          7.698            53000        0.433962   
...          ...            ...              ...             ...   
77531    19100.0         11.261            86600        0.653580   
77532    17700.0         10.662            80900        0.629172   
77533    17600.0         10.595            80300        0.626401   
77534    16300.0         10.068            75300        0.601594   
77535    15600.0          9.742            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  loan_status  
0                    5                 1       22800            0  
1                    3                 0       13600            0  
2                    3                 0       16100            0  
3                    5                 1       22700            0  
4                    5                 1       23000            0  
...                ...               ...         ...          ...  
77531               12                 2       56600            1  
77532               11                 2       50900            1  
77533               11                 2       50300            1  
77534               10                 2       45300            1  
77535                9                 2       42300            1  

[77536 rows x 8 columns]

# Preprocessing

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77536 entries, 0 to 77535
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   loan_size         77536 non-null  float64
 1   interest_rate     77536 non-null  float64
 2   borrower_income   77536 non-null  int64  
 3   debt_to_income    77536 non-null  float64
 4   num_of_accounts   77536 non-null  int64  
 5   derogatory_marks  77536 non-null  int64  
 6   total_debt        77536 non-null  int64  
 7   loan_status       77536 non-null  int64  
dtypes: float64(3), int64(5)
memory usage: 4.7 MB


In [6]:
df.isnull().sum()

loan_size           0
interest_rate       0
borrower_income     0
debt_to_income      0
num_of_accounts     0
derogatory_marks    0
total_debt          0
loan_status         0
dtype: int64

# Logistic Regression model

In [12]:
y= df['loan_status'].values
x= df.drop('loan_status', axis=1)
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=11)

In [13]:
x.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  
0                 1       22800  
1                 0       13600  
2                 0       16100  
3                 1       22700  
4                 1       23000

In [14]:
np.unique(y)

array([0, 1], dtype=int64)

In [17]:
classifier= LogisticRegression()
model= classifier.fit (x_train,y_train)

In [18]:
print(f"Training score: {model.score(x_train,y_train)}")
print(f"Testing score: {model.score(x_test,y_test)}")

Training score: 0.9919521254643004
Testing score: 0.9921584812216261


# Evaluation

In [20]:
y_true=y_test
y_pred= classifier.predict(x_test)
confusion_matrix(y_true, y_pred)

array([[18682,    90],
       [   62,   550]], dtype=int64)

In [21]:
tn, fp,fn,tp =confusion_matrix(y_true, y_pred).ravel()
accuracy= (tp+tn)/(tp+fp+tn+fn)
print(f"Accuracy: {accuracy}")

Accuracy: 0.9921584812216261


# Random Forest model 

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=11)
scaler=StandardScaler().fit(x_train)
x_train_scaled= scaler.transform(x_train)
x_test_scaled= scaler.transform(x_test)
model2= RandomForestClassifier(random_state=11, n_estimators=500).fit(x_train_scaled,y_train)

In [26]:
print(f"Training score: {model2.score(x_train_scaled,y_train)}")
print(f"Testing score: {model2.score(x_test_scaled,y_test)}")

Training score: 0.9973173751547668
Testing score: 0.9920553033429633


In [31]:
y_true=y_test
y_pred= model2.predict(x_test_scaled)
confusion_matrix(y_true, y_pred)

array([[18690,    82],
       [   72,   540]], dtype=int64)

In [32]:
tn, fp,fn,tp =confusion_matrix(y_true, y_pred).ravel()
accuracy= (tp+tn)/(tp+fp+tn+fn)
print(f"Accuracy: {accuracy}")

Accuracy: 0.9920553033429633
